[package]
name = "odds-or-evens-game"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spinners = "4.1.0"

[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"
